npm-admin-client/package.json, npm-client/package.json
- Point package info at the monorepo
=> npm package updates

Cargo.lock, npm-admin-client/package-lock.json, npm-admin-client/package.json, npm-client/package-lock.json, npm-client/package.json, programs/monaco_protocol/Cargo.toml
Diff with rc1 contains
* https://github.com/MonacoProtocol/protocol/pull/19
* https://github.com/MonacoProtocol/protocol/pull/18
=> Update versions to rc2 for audit

programs/monaco_protocol/src/error.rs, programs/monaco_protocol/src/instructions/market/create_market.rs
Price ladder should only have values > 1.0
=> fix: validate new market prices are within range

npm-client/docs/types/market.md, npm-client/types/market.ts
- Type was wrong on MarketPrices for pendingOrders
=> fix: pending Order type on client

admin/util.ts
Will make it easier to target different deployments.
=> feat: allow program address override for admin scripts

npm-client/src/market_query.ts, npm-client/src/order_query.ts, npm-client/types/market.ts, npm-client/types/order.ts, programs/monaco_protocol/src/context.rs, programs/monaco_protocol/src/error.rs, programs/monaco_protocol/src/instructions/order/cancel_order.rs, programs/monaco_protocol/src/instructions/order/mod.rs, programs/monaco_protocol/src/instructions/order/void_order.rs, programs/monaco_protocol/src/lib.rs, programs/monaco_protocol/src/state/order_account.rs, tests/protocol/void_order.ts, tests/util/wrappers.ts
Add instruction for marking orders as voided
=> feat: void order

Cargo.lock, npm-admin-client/package-lock.json, npm-admin-client/package.json, npm-client/package-lock.json, npm-client/package.json, programs/monaco_protocol/Cargo.toml
Protocol: 0.9.0-rc1
Client: 0.6.0-rc1
Admin Client: 4.1.0-rc1
=> chore: update versions to RC1 for 0.9.0 audit

Cargo.lock, programs/monaco_protocol/Cargo.toml, programs/monaco_protocol/src/state/order_account.rs, tests/protocol/close_order.ts
Fix a bug which prevented voided orders from being closed
=> fix: allow voided orders to be closed

admin/client.ts, admin/update_market_status.ts, npm-admin-client/docs/endpoints/market_create.md, npm-admin-client/docs/types/markets.md, npm-admin-client/src/market_create.ts, npm-admin-client/types/markets.ts, npm-client/docs/types/market.md, npm-client/src/market_matching_pool_query.ts, npm-client/src/market_query.ts, npm-client/types/market.ts, package.json
Multiple fixes and updates to the `npm-client` and `npm-admin-client` for the upcoming release.
=> fix: client updates and fixes for inplay release 

programs/monaco_protocol/src/state/market_account.rs
Comment range was incorrect so fixing it.
=> fix: clients don't filter markets by market type

admin/client.ts, admin/product.ts, package.json
Script for quickly creating `product` accounts
=> feat: script for creating products

programs/monaco_protocol/src/instructions/market_position/settle_market_position.rs
=> fix: no outcome max exposure on market position

tests/protocol/crank_settlement.ts
updating settlement anchor test to use newer helpers in order to reduce the amount of code to maintain and make future changes easier
=> chore: updating settlement anchor test to use newer helpers

admin/price_ladders.ts
The new `admin/price_ladders.ts` file was missed from an earlier commit. Adding it back here now.
=> fix: add missing admin script file

npm-admin-client/docs/types/market_outcomes.md, npm-admin-client/types/market_outcomes.ts, npm-client/docs/types/market.md, npm-client/types/market.ts
- Adding in `prices` to market outcome account type in clients
=> fix: add prices on market outcome account in clients

Cargo.lock, npm-admin-client/package-lock.json, npm-admin-client/package.json, npm-client/package-lock.json, npm-client/package.json, programs/monaco_protocol/Cargo.toml
Protocol to 0.15.0-dev
Clients to 12.0.0-dev
=> chore: bump dev versions for 0.15.0

programs/monaco_protocol/src/instructions/matching/on_order_creation.rs, programs/monaco_protocol/src/state/market_matching_queue_account.rs
also doubling the size of the queue
=> fix: order creation should fail if matches cannot be made

programs/monaco_protocol/src/error.rs, programs/monaco_protocol/src/instructions/market/create_market.rs, tests/market/initialize_market_outcome.ts
Release 0.14.0 Audit Issue 2: Missing outcome title length check
Add the check.
=> fix: market outcome creation checks title length

programs/monaco_protocol/src/error.rs, programs/monaco_protocol/src/instructions/market/create_market.rs, programs/monaco_protocol/src/instructions/math.rs, programs/monaco_protocol/src/instructions/order_request/create_order_request.rs, programs/monaco_protocol/src/instructions/price_ladder/add_prices_to_price_ladder.rs
added section validating price value if price ladder is empty; also removed duplicated code for good measure.
=> fix: validating the price precision if price ladder is empty

npm-admin-client/package-lock.json, npm-admin-client/package.json, npm-client/package-lock.json, npm-client/package.json, npm-client/src/market_commission_payment_queues.ts, npm-client/types/market_commission_payment_queue.ts, npm-client/types/market_liquidities.ts, programs/monaco_protocol/src/state/mod.rs, tests/npm-client/market_commission_payment_queue.ts, tests/util/test_util.ts
- `programs/monaco_protocol/src/state/mod.rs` file unnecessarily modified resulting in restricted access
- adding definition of LiquiditySource to client
- removing client side property rename for MarketCommissionPaymentQueue
=> chore: minor updates resolving issue with integrations
