Anchor.toml
programs/monaco_protocol/src/lib.rs

Because of the `features = ` `stable/dev` flags we use for devnet, we must use the vanity address for `localnet` tests

Chore: Use vanity address for yarn tests

---

.pre-commit-config.yaml
admin/add_prices_to_ladder.ts
npm-admin-client/src/market_outcome_prices.ts
package.json
programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/market/create_market.rs
programs/monaco_protocol/src/instructions/market/market_authority.rs
programs/monaco_protocol/src/instructions/market/mod.rs
programs/monaco_protocol/src/instructions/product.rs
programs/monaco_protocol/src/lib.rs
tests/market/create_market.ts
tests/npm-admin-client/market_create.ts
tests/util/wrappers.ts

Any instructions that update or affect a market should only be permitted to be run by the given market's authority.
This PR verifies that the authorised market operator matches the market authority for the below instructions. If the operator does not match the authority then a `MarketAuthorityMismatch` error is returned. 
* `initialize_market_outcome`
* `add_prices_to_market_outcome`
* `update_market_title`
* `update_market_locktime`
* `open_market`
* `settle_market`
* `complete_market_settlement`
* `publish_market`
* `unpublish_market`
*  `suspend_market`
*  `unsuspend_market`
*  `set_market_ready_to_close`
The following changes are also included:
* `yarn build` will now also run `npm install` for each of typescript clients before attempting to `npm run build` on them. 
* Run time args …

fix: restrict market updates to market authority

---

npm-client/docs/endpoints/market_matching_pools.md
npm-client/docs/types/market.md
npm-client/src/market_matching_pools.ts
npm-client/types/market.ts
tests/npm-client/market_matching_pool.ts

Return seeds used for the matching pool PDA addresses along with the addresses/accounts themselves

refactor: return seeds along with matching pools from the client

---

programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/market/update_market_status.rs
programs/monaco_protocol/src/lib.rs
tests/market/update_market_status.ts
tests/util/wrappers.ts

Tightening up operations to settle/close some of the accounts. 
1. Prevent market settlement completing while there is still escrow funds to be returned, i.e., there must still be unsettled orders. This check will mean that by the time `close_market` is called there can be non-settled orders. At least all winnings should have been paid out.
2. Throw an error if an order that is attempted to be closed is not yet complete, i.e., settled or cancelled. 
Ideally `close_market` could be restricted while there still are dependent accounts open but I don't thinkthis is possible with the current data model. E.g., be sure all cancelled orders are closed first.

fix: Additional checks for closing orders/settling markets

---

programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/instructions/market/escrow.rs
programs/monaco_protocol/src/instructions/market/mod.rs
programs/monaco_protocol/src/lib.rs
tests/protocol/close_market.ts

As part of the `close_market` instruction we should also close the `market_escrow` token account.
This closure is done slightly differently as the account is still owned by the `token_program` so needs to be closed via a CPI (the authority is a PDA owned by the monaco program but it is not the owner).

Fix: close escrow as part of `close_market` 

---

Cargo.lock
npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-client/package-lock.json
npm-client/package.json
programs/monaco_protocol/Cargo.toml

Drop RC version suffixes for release. 
NPM packages won't be published until release is deployed to mainnet.

chore: release version 0.6.0

---

npm-client/package-lock.json
npm-client/package.json
npm-client/src/utils.ts
tests/npm-client/stake.ts

TS client fix. 
```
● Stake calculations › JS floating point inaccuracies in stake conversion are not observed
assert.equal(received, expected)
Expected value to be equal to:
2010000
Received:
2009999
```
Uses big.js to safely transform e.g., 2.01 to 2010000. 
This will be released in client version 3.0.1

fix: Accurately convert floating point stake to integer (BN)

---

admin/leaderboard/market_leaderboard.ts
admin/leaderboard/util.ts
npm-admin-client/docs/types/markets.md
npm-admin-client/types/markets.ts
npm-client/docs/endpoints/cancel_order.md
npm-client/docs/endpoints/market_query.md
npm-client/docs/endpoints/order_query.md
npm-client/docs/types/order.md
npm-client/src/cancel_order.ts
npm-client/src/market_query.ts
npm-client/src/order.ts
npm-client/src/order_query.ts
npm-client/types/market.ts
npm-client/types/order.ts
tests/npm-admin-client/market_management.ts
tests/npm-client/market_query.ts
tests/npm-client/my_orders.ts
tests/npm-client/order_query.ts

* fixing enum type returned by anchor when fetching accounts (it's an object rather than just raw int as stored on chain)

fix!: client type wrappers for enums that anchor returns

---

Cargo.lock
npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-admin-client/src/market_management.ts
programs/monaco_protocol/Cargo.toml
programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/instructions/market/escrow.rs
programs/monaco_protocol/src/instructions/market/update_market_status.rs
programs/monaco_protocol/src/instructions/transfer.rs
programs/monaco_protocol/src/lib.rs
tests/market/update_market_status.ts
tests/util/wrappers.ts

Successful market settlement expects program transfers in and out of escrow to balance, resulting in an account balance of 0 tokens. There is an explicit check to ensure settlement only fully completes when escrow's balance equals 0. 
If someone manually transfers tokens to escrow then this check will prevent settlement from completing.
An alternative method of tracking the program transfers to/from escrow will be required to continue to allow this check at settlement time. 
For now, this PR will move the balance check from settlement complete to the instruction for moving a market status from Settled to ReadyToClose. In addition a new instruction has been added to allow a market authority to transfer any surplus balance, post settlement completing successfully, from escrow, enabling all …

fix: unblock settlement where market escrow has been transferred to

---

npm-admin-client/docs/endpoints/market_management.md
npm-admin-client/src/market_management.ts
tests/npm-admin-client/market_management.ts
tests/util/wrappers.ts

If additional tokens have been transferred to a market escrow token account, outside of normal protocol operation, the market operator will need some way to remove that surplus balance of tokens so the account can be later closed. Work to support this was added in #38 but the client was not updated. This PR updates the admin client to make it easy to use that functionality.

feat: Add transferMarketEscrowSurplus to admin-client

---

Cargo.lock
programs/monaco_protocol/Cargo.toml
programs/monaco_protocol/src/instructions/market/create_market.rs

The existing method for checking the decimal precision of provided prices for a price ladder suffers from some rounding issues, e.g., 9.9999 would pass a check attempting to ensure numbers with a maximum of 3 decimals places were used. 
This PR replaces that method for checking the precision with a new method using `rust_decimal`. I needed to bump that dependency to get access to `trunc_with_scale()` so I went to the latest `1.29.0`. It doesn't seem to be compatible with the solana build toolchain in 1.13.x so it now needs to be built with 1.14.x (1.14.16).

fix: improve decimals check and close off edge cases

---

npm-client/docs/types/market_position.md
npm-client/types/market_position.ts

A small miss from the client changes for the 0.9.0 release

fix(client): add missing payer field to MarketPosition account type

---

jest.config.js
programs/monaco_protocol/src/instructions/matching/matching_pool.rs
programs/monaco_protocol/src/state/market_account.rs
tests/protocol/cancel_order.ts

There is an issue whereby cancelling an order in an inplay market could result in incorrectly affecting the total available liquidity in a matching pool.  
A delayed order's liquidity isn't added to the total liquidity for a matching pool until the delay for the order has expired (is in the past) and either:
* `process_delay_expired_orders` is called for the matching pool containing the order, or
* `match_orders` is called for the order or some other delay expired order at the front of the same matching queue
The issue arises when the order is cancelled between the order's delay expiring and its liquidity being added to the total available liquidity. There is an attempt to subtract the order's liquidity from the total but it has not been added to the total yet. The result being, either …

fix: don't subtract an order's liquidity from MarketMatchingPool available liquidity on cancel if its not yet been added to the total

---

npm-admin-client/docs/endpoints/market_management.md
npm-admin-client/src/market_management.ts
tests/npm-admin-client/market_management.ts

This PR adds 2 new endpoints to the admin client:
- `updateMarketEventStartTime`
- Set the event start time on a market to the specified `EpochTimeStamp`
- `setMarketEventStartToNow`
- Set the event start time on a market to `now`

feat: admin-client - add endpoints to update event start time on a market account

---

programs/monaco_protocol/src/context.rs

Error used during post event start cancellation of pre-event orders was incorrect when an incorrect Market account was provided to the instruction.

fix: CancelationPurchaserMismatch should be CancelationMarketMismatch

---

programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
tests/protocol/cancel_preplay_order_post_event_start.ts

After a cancellation if the matching/liquidity pool isn't transitioned to inplay already then the pool isn't updated to reflect the cancelled order and looks like it still contains pre-event liquidity even though at least some of that liquidity has been refunded.
This change will reset the pool, transitioning it for inplay, during the first order cancellation if it hasn't been transitioned already. This will remove the chance for the pool to be inconsistent and showing no-longer available liquidity.

fix: transition matching pools asap, don't leave pool inconsistent 

---

programs/monaco_protocol/src/instructions/market_position/settle_market_position.rs
programs/monaco_protocol/src/instructions/math.rs

Currently if total commisison exceeds profit there is a chance that product commission will be over-charged. With this fix we ensure that product profit can not exceed the total amount of available profit.

fix: reduce product commission where total commission exceeds profit

---

npm-admin-client/package-lock.json
npm-admin-client/package.json

Unfortunately version 5.0.0 was lost to us.

chore: set admin client version for 0.10.0 protocol release

---

programs/monaco_protocol/src/instructions/market/create_market.rs
programs/monaco_protocol/src/instructions/market/update_market_event_start_time.rs
programs/monaco_protocol/src/instructions/matching/matching_pool.rs
programs/monaco_protocol/src/instructions/order/cancel_order.rs
programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
programs/monaco_protocol/src/instructions/order/create_order.rs
programs/monaco_protocol/src/state/market_account.rs
tests/end-to-end/inplay_market.ts
tests/protocol/cancel_preplay_order_post_event_start.ts
tests/protocol/create_order.ts
tests/protocol/move_market_matching_pool_to_inplay.ts

Fixes #81 
This addresses the issue raised in #81 ,  updating the protocol to not rely only on a market's `inplay` flag to determine whether the market is in play/in running/live yet, but rather will fall back on checking the market's event start timestamp also. 
```Rust
market.inplay || (market.inplay_enabled && market.event_start_timestamp <= now)
```
This change now means that orders placed on or after a market's event start timestamp will be treated properly as inplay orders - triggering an orderbook reset if the market is configured to do so - and will no longer be considered to be included in or matched against pre-event start liquidity.

fix: market inplay transition issue

---

Cargo.lock
programs/monaco_protocol/Cargo.toml
programs/monaco_protocol/src/instructions/market/create_market.rs
programs/monaco_protocol/src/instructions/market/update_market_event_start_time.rs
programs/monaco_protocol/src/instructions/matching/matching_pool.rs
programs/monaco_protocol/src/instructions/order/cancel_order.rs
programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
programs/monaco_protocol/src/instructions/order/create_order.rs
programs/monaco_protocol/src/state/market_account.rs
tests/end-to-end/inplay_market.ts
tests/protocol/cancel_preplay_order_post_event_start.ts
tests/protocol/create_order.ts
tests/protocol/move_market_matching_pool_to_inplay.ts

fix: market inplay transition issue (see full details on #82)
* This addresses the issue raised in https://github.com/MonacoProtocol/protocol/issues/81 , updating the protocol to not rely only on a market's inplay flag to determine whether the market is in play/in running/live yet, but rather will fall back on checking the market's event start timestamp also.

release: 0.10.1

---

programs/monaco_protocol/src/instructions/clock.rs
programs/monaco_protocol/src/instructions/market/create_market.rs
programs/monaco_protocol/src/instructions/market/update_market_event_start_time.rs
programs/monaco_protocol/src/instructions/market/update_market_locktime.rs
programs/monaco_protocol/src/instructions/matching/matching_one_to_one.rs
programs/monaco_protocol/src/instructions/matching/matching_pool.rs
programs/monaco_protocol/src/instructions/mod.rs
programs/monaco_protocol/src/instructions/order/cancel_order.rs
programs/monaco_protocol/src/instructions/order/create_order.rs
programs/monaco_protocol/src/lib.rs
programs/monaco_protocol/src/state/market_account.rs

Enables functions that rely on clock time to be united tested. The Clock sysvar which is used when running on the solana runtime to get the current time is not available when running `cargo test`. This changes enables the use of SystemTime when running `cargo test` but otherwise uses the `Clock` sysvar to get the current timestamp.

fix: allow unittests to use clock time

---

npm-admin-client/src/market_helpers.ts
npm-admin-client/src/market_outcome_prices.ts
npm-client/src/create_order.ts
npm-client/src/market_matching_pool_query.ts
npm-client/src/market_outcome_query.ts
npm-client/src/market_query.ts
npm-client/src/order_query.ts
npm-client/src/product.ts
npm-client/src/product_query.ts
npm-client/src/trade_query.ts
tests/protocol/create_order.ts
tests/util/test_util.ts
tests/util/wrappers.ts

The client code should not hardcode commitment levels when making rpc calls, it should instead rely on the provider settings
Based on: https://docs.solana.com/developing/transaction_confirmation#use-an-appropriate-preflight-commitment-level

refactor: remove all hardcoded commitment levels from client

---

Cargo.lock
README.md
npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-client/package-lock.json
npm-client/package.json
programs/monaco_protocol/Cargo.toml

Both clients get major bumps due to tx confirmation changes.
Updated readme to split the date away from the code release so we can cut and complete the code release without worrying about the upgrade date. Code release dates are tag/github release dates anyway.

chore: set versions and update readme for 0.11.0 protocol release

---

programs/monaco_protocol/src/instructions/clock.rs

Test code to retrieve system time has a potentially (though unrealistically) unsafe cast from u64 to i64. The solana library uses i64 to represent a timestamp so we're stuck using that as the target type. 
This change makes it clear that we're returning i64 due to the Solana lib (UnixTimestamp is an alias for i64), and caps the value to `i64::MAX`. 
Realistically the Solana timestamp type will need to be updated before our unit tests failing have issues with this clamp/ceil of the return value.

fix: ceil test timestamps at i64::max

---

programs/monaco_protocol/src/state/market_account.rs
programs/monaco_protocol/src/state/payments_queue.rs

`usize` to `u32` conversions can be potentially unsafe on 64-bit machines, use `u32` explicitly when creating queues

fix: use u32 when creating queues

---

programs/monaco_protocol/src/instructions/math.rs
programs/monaco_protocol/src/instructions/order/create_order.rs

There is a potentially unsafe cast of `stake` in `stake_precision_is_within_range` from `u64` to `i64`. Refactor to remove the need to down cast to `i64`.

fix: stake was cast to i64 for check, refactor to prevent loss of data

---

programs/monaco_protocol/src/state/market_position_account.rs

There is potential unsafe cast from `i128` to `u64` at line 49 in `total_exposure` method. Auditors suggested to use `u64::try_from` instead.

fix: postmatch exposure was cast to u64 in an unsafe way

---

programs/monaco_protocol/src/instructions/mod.rs
programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
programs/monaco_protocol/src/instructions/transfer.rs
programs/monaco_protocol/src/lib.rs
tests/end-to-end/inplay_market.ts
tests/protocol/cancel_preplay_order_post_event_start.ts

Issue of data erasure was raised https://github.com/MonacoProtocol/protocol/issues/117.
To address it a new check will be added to see if there is anything to cancel. If not it throws an error.
```
require!(
order.stake_unmatched > 0_u64,
CoreError::CancelOrderNotCancellable
);
```
Additionally signature of `cancel_preplay_order_post_event_start` method was rewritten to allow unit testing. As a side effect transfer logic had to be moved to the `lib.rs` until we find a way to unit test CPI calls.

fix: stoping void stake override on repeated cancelation

---

programs/monaco_protocol/src/instructions/matching/matching_pool.rs
programs/monaco_protocol/src/instructions/order/cancel_order.rs
programs/monaco_protocol/src/instructions/order/create_order.rs

we were using queue and pool interchangeably (probably because the implementation is a queue) but that's confusing so fixing it.

chore: cleaning up the naming around matching pools

---

programs/monaco_protocol/src/events/mod.rs
programs/monaco_protocol/src/events/trade.rs
programs/monaco_protocol/src/instructions/matching/matching_one_to_one.rs
programs/monaco_protocol/src/lib.rs

This emits an event when a trade (pair) is created, capturing the amount, price, and market pk of the trade. This occurs during the `matchOrders` instruction. 
The intention is to make this data (cheaply) available to analytics tools such as Dune. 
On e.g., Dune, example data that is outputted could be decoded as follows:
```
select 
bytearray_to_bigint(bytearray_reverse(bytearray_substring(from_base64('vdt/007mYe4ALTEBAAAAAAAAAAAAAABAQnyrqOfbyTtv63oJAcHyZaE71Kr3jXhScLqcVV+Gpd0='), 9, 8))) as amount,
from_ieee754_64(bytearray_reverse(bytearray_substring(from_base64('vdt/007mYe4ALTEBAAAAAAAAAAAAAABAQnyrqOfbyTtv63oJAcHyZaE71Kr3jXhScLqcVV+Gpd0='), 17, 8))) as price,
to_base58(bytearray_substring(from_base64('vdt/007mYe4ALTEBAAAAAAAAAAAAAABAQnyrqOfbyTtv63oJAcHyZaE71Kr3jXhScLqcVV+Gpd0='), 25, …
```

feat: emit event capturing basics of a trade

---

admin/client.ts
admin/create_market.ts
admin/create_order.ts
npm-admin-client/docs/endpoints/market_create.md
npm-admin-client/src/market_create.ts
package.json

Missed some small bits for the new price ladder functionality
* add admin script to help create/manage the new `PriceLadder` accounts
* update `createMarketWithOutcomesAndPriceLadder` client function to allow price ladder account public keys to be passed in
* update the example admin script for creating markets to use a price ladder account address, not an array of prices.

fix: enable price ladder changes in client and scripts

---

programs/monaco_protocol/src/instructions/matching/create_trade.rs
programs/monaco_protocol/src/instructions/matching/matching_one_to_one.rs

We have agreed to move away from passing Anchor's wrapper types that are hard to mock for testing.
Additionally changing name of the method to `create_trade` from `initialize_(...)` since we use that more often.

refactor: trade creation method update

---

npm-admin-client/docs/endpoints/market_helpers.md
npm-admin-client/src/market_create.ts
npm-admin-client/src/market_helpers.ts
programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/instructions/market/create_market.rs
programs/monaco_protocol/src/state/market_matching_queue_account.rs
programs/monaco_protocol/src/state/mod.rs
tests/end-to-end/inplay_market.ts
tests/market/create_market.ts
tests/market/recreate_market.ts
tests/protocol/close_market_settlement.ts
tests/protocol/close_market_voided.ts
tests/util/test_util.ts
tests/util/wrappers.ts

Introducing market matching queue account. Protocol was updated to create the account during market creation and close it when market is closed. Nothing more.
This change is safe to go to production even if we do not push the matching changes themselves. The only consequence is that market creation will become slightly more expensive.

feat: introducing market matching queue account

---

programs/monaco_protocol/src/state/market_matching_pool_account.rs

With the number and size of accounts being passed in the context `MatchOrders` to the instruction `match_orders`, and the new addition of `emit!`ing the `TradeEvent` it is possible to run out of heap space and to cause a `match_orders` instruction to panic. 
We have measured heap usage for `match_orders`, before any instruction code is executed, at ~29kB. The newly added trade event functionality uses about 1kB which is bringing average usage of the instruction very close to the 32kB limit, and apparently in some scenarios bringing it beyond 32kB. 
This PR reduces the length of the `MarketMatchingPool` queue from 100 to 80, and so reduces the overall size of those accounts. Reducing the queue size brings heap usage before any `match_orders` instruction code is executed down from ~29kB to …

fix: reduce MMP queue size to reduce heap usage during match_orders

---

programs/monaco_protocol/src/instructions/market/escrow.rs

Transferring market escrow surplus should only be allowed after all other transfers were executed and before market gets closed. The market status indicating that is currently either `Settled` or `Voided`. Therefor removing the `ReadyToClose` which would allow funds to be lost.

fix: surplus can only be transferred out when settled or voided and before closure

---

programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
programs/monaco_protocol/src/instructions/order/settle_order.rs
programs/monaco_protocol/src/lib.rs
tests/end-to-end/inplay_market.ts

If order was canceled as a whole it should not go through settlement process since it was already paid out (or rather paid back). To keep the market consistency counters correct it means the cancel method needs to decrement them now when needed.

fix: canceled orders should not be allowed to be settled again

---

programs/monaco_protocol/src/instructions/matching/matching_one_to_one.rs
programs/monaco_protocol/src/state/market_position_account.rs
tests/protocol/product_commission_matching.ts

One of the edge cases of our matching algorithm is that orders owned by the same users can be matched. Let's suppose they were created in the context of two separate products in which case both should be recorded accordingly. Unfortunately this was not happening correctly and that's what's being fixed here.

fix: copy product commission contributions when matching orders

---

programs/monaco_protocol/src/instructions/matching/matching_one_to_one.rs
tests/protocol/product_commission_matching.ts

part 2 to https://github.com/MonacoProtocol/protocol/pull/149
> One of the edge cases of our matching algorithm is that orders owned by the same users can be matched. Let's suppose they were created in the context of two separate products in which case both should be recorded accordingly. Unfortunately this was not happening correctly and that's what's being fixed here.
Forgot to copy the sum as well as parts of the matched risk.

fix: copy product commission contributions when matching orders (2)

---

programs/monaco_protocol/src/instructions/market/create_market.rs
tests/market/create_market.ts

Remove missed existing validation conditions that incorrectly allowed empty string to be provided as market type discriminator and/or market type value during market creation when they should have been `null`/`None` according to the market type used.

fix: remove empty string market type discrim and value condition from market creation

---

programs/monaco_protocol/src/state/market_matching_queue_account.rs

since the account is not gonna be used yet make it cheaper by reducing the size

chore: minimise size of the account to lower the fees

---

npm-admin-client/src/market_management.ts
programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/close.rs
programs/monaco_protocol/src/instructions/market/create_market.rs
programs/monaco_protocol/src/instructions/market/update_market_status.rs
programs/monaco_protocol/src/lib.rs
tests/end-to-end/inplay_market.ts
tests/market/recreate_market.ts
tests/protocol/close_market_outcome.ts
tests/protocol/close_market_settlement.ts
tests/protocol/close_market_voided.ts
tests/protocol/void_order.ts
tests/util/test_util.ts
tests/util/wrappers.ts

* Create `matching_queue` & `commission_payment_queue` when opening market (rather than market creation)
* Add a new instruction `close_market_queues` to close the above queues (rather than closing using close_market)
* Some test refactoring

feat: create queues when opening markets

---

npm-admin-client/docs/endpoints/market_helpers.md
npm-admin-client/src/market_helpers.ts
npm-admin-client/src/market_management.ts
programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/close.rs
programs/monaco_protocol/src/instructions/market/update_market_status.rs
programs/monaco_protocol/src/lib.rs
programs/monaco_protocol/src/state/market_liquidities.rs
programs/monaco_protocol/src/state/mod.rs
tests/end-to-end/inplay_market.ts
tests/protocol/close_market_settlement.ts
tests/protocol/close_market_voided.ts
tests/util/test_util.ts
tests/util/wrappers.ts

Second account needed to deliver improved matching. This account holds summary of the unmatched liquidity available on the market.

feat: market liquidities account

---

Cargo.lock
programs/monaco_protocol/Cargo.toml
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/close.rs
programs/monaco_protocol/src/instructions/market_position/settle_market_position.rs
programs/monaco_protocol/src/instructions/order/settle_order.rs
programs/monaco_protocol/src/lib.rs

This updates 0.13.0 with 
* a dependency bump for the Protocol Product program, now targeting the audited v0.2.0 release which includes the upgrade to anchor 0.29.0
* An improvement for settlement of orders and market positions to keep market state checks consistent for the different settlement instructions
* An improvement to closure of market positions during market closure, giving better protection from bugs affecting the market status and/or market settled_account_counts, reducing the likelihood of ever closing a market position before it has been paid out.

chore: dependency bump and audit fixes for release 0.13.0

---

npm-client/docs/endpoints/cancel_order_instruction.md
npm-client/src/cancel_order_instruction.ts
tests/order/cancelation_payment_10.ts
tests/order/cancelation_payment_11.ts
tests/util/test_util.ts

Removing an old helper method `cancelOrderSmart` that was superseded by simpler wrapper `cancel` method.

chore: removing a deprecated test helper method

---

programs/monaco_protocol/src/state/market_matching_pool_account.rs
programs/monaco_protocol/src/state/market_matching_queue_account.rs

matching pool: peek should not need to have self mutable
matching queue: peek should not need to have self mutable, however mutable version is needed so creating two versions of the method

chore: updating peek and adding peek_mut methods

---

programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/market/update_market_status.rs
programs/monaco_protocol/src/lib.rs
programs/monaco_protocol/src/state/market_account.rs
programs/monaco_protocol/src/state/payments_queue.rs
tests/market/update_market_status.ts
tests/util/wrappers.ts

Settlement shouldn't be called "complete" until all payouts, and commission payments are complete. The check that the unsettled account count is 0 ensures that payouts are complete. To ensure that the commission payments are complete the queue must be passed in and checked that it is empty. 
Also refactored a few unit tests when adding a `mock_market` test helper to `market_account.rs`, and adding some new tests to cover `complete_settlement`.

fix: check payments queue on completeSettlement

---

Cargo.lock
npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-client/package-lock.json
npm-client/package.json
programs/monaco_protocol/Cargo.toml

Bump versions and add `-dev` suffix following 0.13.0 release.

chore: bump dev versions for 0.14.0

---

npm-client/src/cancel_order_instruction.ts
programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/order/cancel_order.rs
programs/monaco_protocol/src/instructions/order/settle_order.rs
tests/end-to-end/inplay_market.ts
tests/protocol/cancel_order.ts
tests/protocol/close_market_outcome.ts
tests/protocol/close_market_position.ts
tests/protocol/close_market_settlement.ts
tests/protocol/close_market_voided.ts
tests/protocol/close_order.ts
tests/protocol/close_trade.ts
tests/protocol/crank_settlement.ts
tests/util/test_util.ts
tests/util/wrappers.ts

Ensure that `payer` where relevant is where rent exemption fees are refunded to, rather than `purchaser` when data accounts are closed.

fix: ensure fee payer (if custom) is refunded when accounts are closed

---

programs/monaco_protocol/src/state/market_matching_pool_account.rs

MMP's Cirque was recently updated not to initialise full of default values but rather to just initialise as empty and grow into the space that is required. This should help with serdes given there tends to be so many MMPs created but with few orders in many. 
A bug was introduced at this point, as enqueue could no longer arbitrarily index into the full size storage vector, the vector had to be grown when appropriate on enqueue, or if possible, indexed into to replace some existing data. The condition to grow/push rather than replace was a little too greedy, and so it was possible that a new value enqueued after a value had been removed ended up being placed at the end of the storage vec, rather than replacing the element after the end of the queue. 
An alternative fix would be to prune …

fix: if back is not at end of vec enqueue must insert by index

---

npm-client/src/cancel_order_instruction.ts
programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/market/move_to_inplay.rs
programs/monaco_protocol/src/instructions/matching/matching_pool.rs
programs/monaco_protocol/src/instructions/order/cancel_order.rs
programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
programs/monaco_protocol/src/instructions/order_request/process_order_request.rs
programs/monaco_protocol/src/instructions/transfer.rs
programs/monaco_protocol/src/lib.rs
programs/monaco_protocol/src/state/market_account.rs
programs/monaco_protocol/src/state/market_liquidities.rs
programs/monaco_protocol/src/state/market_matching_pool_account.rs
tests/end-to-end/inplay_market.ts
tests/protocol/cancel_order.ts
tests/util/wrappers.ts

includes commit from #179 
When a market that is configured to zero the orderbook at event start a number of accounts need to be updated and some of this handling was missed with the introduction of order requests and the market liquidity account. 
Market Liquidities need to be reset. 
Market matching pools (MMPs) need to be set to length zero and liquidity totals set to zero. 
Market needs its flag set to true. 
This PR ties resetting the MarketLiquidities account to setting the `inplay` flag on `Market`. This ensures liquidities are only reset once. MMPs already have a flag. 
There are trustless instructions to trigger all of these actions. 
We also have to consider if market/liquidity interactions occur before some or all of these instructions are triggered. The three interactions to …

fix: update handling of liquidity queues and pools at inplay transition

---

programs/monaco_protocol/src/state/market_matching_queue_account.rs

redoing unit tests for MatchingQueue to ensure proper coverage by 1) merging some test and 2) adding test that make sure that underlaying circular array implementation works correctly

chore: redoing unit tests for MatchingQueue to ensure proper coverage

---

tests/market/create_market.ts

looks like test  for market creation had some accounts passed that are no longer needed

fix: removing accounts that were droped from the endpoint

---

Cargo.lock
README.md
npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-client/package-lock.json
npm-client/package.json
programs/monaco_protocol/Cargo.toml

Some additional changes have been taken in from develop. We need to reset the versions in the release branch.

chore: bump dev versions for 0.14.0 (again)

---

programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/matching/on_order_match.rs
tests/protocol/process_order_match.ts

Release 0.14.0 Audit Issue 1: Missing `outcome_index` check in `process_order_match` endpoint
I've opted to add validation to `market_matching_pool` to make sure it matches the outcome of the `market_matching_queue`. By extension it means that the `maker_order` is correct as well.

fix: process_order_match endpoint validates matching_pool outcome

---

programs/monaco_protocol/src/state/market_order_request_queue.rs
tests/orderRequest/createOrderRequest.ts

[L-01] DoS in create_order_request
The current check for `OrderRequest` equality is too strict, and will allow for `OrderRequest`s to be enqueued which could cause conflicts when processed.
i.e. multiple `OrderRequest`s could be successfully enqueued if they had the same `purchaser`, `distinct_seed` but a differing `stake`,  but this would then fail to process into an `Order` as the seeds would conflict.
We should ensure only that `purchaser` and `distinct_seed` are unique when enqueueing items, as these are the seeds used when processing the queue to create `Order`s.

fix: prevent duplicate `order_request` enqueueing

---

programs/monaco_protocol/src/context.rs
tests/util/wrappers.ts

`CancelOrderPostMarketLock` context contained unnecessary `market_matching_pool`.

fix: unnecessary market_matching_pool in context

---

Cargo.lock
npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-client/package-lock.json
npm-client/package.json
programs/monaco_protocol/Cargo.toml

Dropping the `-dev` suffix from TS client and Protocol program versions for release of 0.14.0

chore: drop -dev from versions for 0.14.0 release

---

Cargo.lock
npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-client/package-lock.json
npm-client/package.json
programs/monaco_protocol/Cargo.toml

They flipped back to 0.14.0 when main was merged into develop. Fixing develop back to the dev versions for 0.15.0

chore: bump dev versions for 0.15.0

---

Cargo.lock
npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-client/docs/endpoints/create_order_instruction.md
npm-client/docs/types/order.md
npm-client/package-lock.json
npm-client/package.json
npm-client/src/create_order.ts
npm-client/src/create_order_instruction.ts
npm-client/types/order.ts
programs/monaco_protocol/Cargo.toml
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/market_position/update_on_order_match.rs
programs/monaco_protocol/src/instructions/matching/on_order_match.rs
programs/monaco_protocol/src/instructions/order/cancel_order_post_market_lock.rs
programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
programs/monaco_protocol/src/instructions/order_request/create_order_request.rs
programs/monaco_protocol/src/instructions/order_request/dequeue_order_request.rs
programs/monaco_protocol/src/instructions/order_request/process_order_request.rs
programs/monaco_protocol/src/lib.rs
programs/monaco_protocol/src/state/market_order_request_queue.rs
tests/orderRequest/createOrderRequest.ts
tests/orderRequest/processOrderRequest.ts
tests/util/wrappers.ts

Introducing `expiresOn` optional property during creation of order request. If set the value is evaluated:
- firstly on creation where stops adding request if transaction is processed late
- secondly on processing where stops order being created and all funds taken during creation being refunded

feat: order request expiry

---

npm-admin-client/package-lock.json
npm-admin-client/package.json
npm-client/package-lock.json
npm-client/package.json
npm-client/src/market_commission_payment_queues.ts
npm-client/src/market_matching_queues.ts
npm-client/src/market_order_request_queues.ts
tests/npm-client/market_commission_payment_queue.ts
tests/npm-client/market_matching_queue.ts
tests/npm-client/market_order_request_queue.ts

Change fixes the the issue of property translation for Commission Payments. Additionally it adds to all the queues method fetching pks only.

chore: queue client fixes and improvements 

---

programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/market/update_market_status.rs
programs/monaco_protocol/src/instructions/math.rs
tests/order/matching_orders_03.ts
tests/util/wrappers.ts

The cross-matching code is written in a way that can handle markets with any number of outcomes. However, the more outcomes there is the more compute units it requires and the worry that transactions start to fail.
So done some testing and looks like at about 7 outcomes standard 20k of compute units is no longer enough on occasion to create orders with cross matching enabled (8 outcomes is 100% failure).
Based on that then I've decided to limit number of outcomes allowed for cross-matching market to 5.

chore: introducing check for number of outcomes to enable cross matching

---

programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
tests/protocol/process_order_match.ts

Adding validation to `ProcessOrderMatchTaker` to make sure `MarketMatchingQueue` head is a "taker".
Adding validation to `ProcessOrderMatchMaker` to make sure `MarketMatchingQueue` head is a "maker".
In both cases making sure that the error returned is very clear.

fix: validating that matching queue head is the right type

---

programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/error.rs
programs/monaco_protocol/src/instructions/market_liquidities/update_market_liquidities_with_cross_liquidity.rs
programs/monaco_protocol/src/lib.rs
tests/order/matching_orders_02.ts
tests/protocol/update_market_liquidities_with_cross_liquidity.ts
tests/util/wrappers.ts

Fixing issues with `update_market_liquidities_with_cross_liquidity` safety.
Removing `cross_liquidity` as it was inconsequential due to method determining its own cross price and stake.
Adding more validations to make it safer:
- validating that number of passed sources is 1 less that number of outcomes for this market
- validating that there is no duplicate outcome sources
- validating that there is no incorrect outcomes
- sorting source liquidities provided by outcome to make sure that all variations end up in the same liquidity bucket

fix: update_market_liquidities_with_cross_liquidity updates

---

programs/monaco_protocol/src/state/market_order_request_queue.rs

Extending queue to `75` elements (from 30) to better handle big spikes in requests. This change will increase rent to `~0.070 SOL`, which is `x2.4` more than previously. It also pushes the `MarketOrderRequestQueue` account size up to `10,028` which is close to the limit of `10,240` for PDA accounts.

chore: extending MarketOrderRequestQueue

---

programs/monaco_protocol/src/instructions/matching/matching_pool.rs
programs/monaco_protocol/src/instructions/matching/on_order_creation.rs
programs/monaco_protocol/src/instructions/order/cancel_order.rs
programs/monaco_protocol/src/lib.rs
programs/monaco_protocol/src/state/market_liquidities.rs
programs/monaco_protocol/src/state/market_matching_pool_account.rs
programs/monaco_protocol/src/state/market_position_account.rs
programs/monaco_protocol/src/state/order_account.rs
tests/order/cancelation_payment_10.ts
tests/order/cancelation_payment_12.ts
tests/order/matching_orders_03.ts
tests/protocol/cancel_order.ts

In a  matching approach introduced by v14 makers are at disadvantage when it comes to order cancelation. When the maker order gets created, its liquidity is added to `MarketLiquidities` account. If any portion of that liquidity gets matched  maker order is impossible to cancel until the match gets processed. This is because `unmatched_stake` of the maker order does not get updated (reduced in that case) till match gets post-processed while it is being used to determine amount being canceled. Since that amount can be bigger than available liquidity it leads to an error until match is processed.
A partial cancel based on available liquidity should happen, leaving enough `unmatched_stake` to be matched in post-processing.
One of the interesting consequences of this and asynchronicity of …

fix: partial cancelation based on available liquidity

---

Cargo.lock
programs/monaco_protocol/Cargo.toml
programs/monaco_protocol/src/state/market_order_request_queue.rs
tests/protocol/create_order_request.ts

We have raised queue length to `75` but that have resulted in 
```
logs: [
'Program monacoUXKtUi6vKsQwaLyxmXKSievfNWEcYXTgkbCih invoke [1]',
'Program log: Instruction: CreateOrderRequest',
'Program 11111111111111111111111111111111 invoke [2]',
'Program 11111111111111111111111111111111 success',
'Program log: Error: memory allocation failed, out of memory',
'Program monacoUXKtUi6vKsQwaLyxmXKSievfNWEcYXTgkbCih consumed 90035 of 200000 compute units',
'Program monacoUXKtUi6vKsQwaLyxmXKSievfNWEcYXTgkbCih failed: SBF program panicked'
],
```
After investigation we have determined that when queue length was to be changed from `55` to `56` the memory reallocation caused by `Vec` implementation to temporarily exceed transaction's limit and cause error.

release: v0.15.2

---

programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/instructions/order/cancel_order_post_market_lock.rs
programs/monaco_protocol/src/lib.rs
tests/protocol/cancel_order_post_market_lock.ts
tests/util/wrappers.ts

Updates `cancel_order_post_market_lock` to behave the same as `cancel_order` with respect to updating market liquidities and the relevant matching pool. 
Some changes coming in the pending release will allow for the unit testing that I've had to disable to be restored. 
I also updated the integration test to ensure that the market liquidities and the matching pool are updated to reflect the cancellation. 
Here is the test failure against `main`
```
FAIL  tests/protocol/cancel_order_post_market_lock.ts (20.061 s)
Security: Cancel Order Post Market Lock
✕ success: unmatched order (8071 ms)
✓ failure: matched order (11373 ms)
● Security: Cancel Order Post Market Lock › success: unmatched order
assert.deepEqual(received, expected)
Expected value to deeply equal to:
[{"stakeUnmatched": 0, …
```

fix: update liquidities and matching pool on postlock cancel

---

programs/monaco_protocol/src/context.rs
programs/monaco_protocol/src/instructions/market/move_to_inplay.rs
programs/monaco_protocol/src/instructions/market_position/update_on_order_cancellation.rs
programs/monaco_protocol/src/instructions/order/cancel_order.rs
programs/monaco_protocol/src/instructions/order/cancel_order_post_market_lock.rs
programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
programs/monaco_protocol/src/lib.rs
tests/protocol/cancel_order.ts
tests/protocol/cancel_preplay_order_post_event_start.ts

Reducing differences between cancel endpoints to minimum. There are 3 endpoints:
- `cancel_order`
- `cancel_order_post_market_lock`
- `cancel_preplay_order_post_event_start`.
Endpoints `cancel_order` and `cancel_order_post_market_lock` are most similar. They share the code that does the cancelation. The difference is in precondition for the code execution. Additionally `cancel_order` needs to account for markets transition into Inplay mode, where `cancel_order_post_market_lock` does not.
Endpoints `cancel_order` and `cancel_preplay_order_post_event_start` use a new `move_market_to_inplay_if_needed` function which is more convenient to use, reduces code duplication and simplifies this operation.
Endpoint `cancel_order_post_market_lock` no longer checks matching queue being empty since …

chore: cancel endpoints review

---

programs/monaco_protocol/src/instructions/order/cancel_preplay_order_post_event_start.rs
programs/monaco_protocol/src/instructions/order/settle_order.rs
programs/monaco_protocol/src/state/order_account.rs

It was overlooked that after `void_stake_unmatched_by` can be used to partially match `void_stake_unmatched` can still be called on market transitions, leading to order data being scrambled. Fixed it by updating `void_stake_unmatched` being now a wrapper around `void_stake_unmatched_by`.

fix: void_stake_unmatched now calls void_stake_unmatched_by
